name = 'AWS User Group Theme'
license = 'MIT'
licenselink = 'https://github.com/kkeles/awsug-hugo/LICENSE'
description = 'Common theme for websites of AWS User Groups'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/kkeles/awsug-hugo'

# If you have a running demo of the theme
demosite = 'https://aws-user-group.berlin'


# If the theme has a single author
[author]
  name = 'Kadir Keles'
  homepage = 'https://kadirkeles.com'
